/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkflowRunStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Text,
  'running' : IDL.Null,
});
export const Time = IDL.Int;
export const WorkflowRun = IDL.Record({
  'id' : IDL.Text,
  'status' : WorkflowRunStatus,
  'provider' : IDL.Text,
  'inputs' : IDL.Text,
  'timestamp' : Time,
  'outputBlobId' : IDL.Opt(IDL.Text),
  'workflowType' : IDL.Text,
  'durationNanos' : IDL.Opt(IDL.Int),
});
export const APIKey = IDL.Record({
  'key' : IDL.Text,
  'provider' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const CustomProviderMetadata = IDL.Record({ 'displayName' : IDL.Text });
export const ProviderInfo = IDL.Record({
  'documentationLink' : IDL.Text,
  'name' : IDL.Text,
  'author' : IDL.Text,
  'version' : IDL.Text,
  'apiEndpoint' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'provider' : IDL.Text,
  'fromSystem' : IDL.Bool,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateAPIKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelPendingWorkflowRunsForProvider' : IDL.Func([IDL.Text], [], []),
  'cancelWorkflowRun' : IDL.Func([IDL.Text], [], []),
  'customProviderMetadataExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'executeWorkflow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [WorkflowRun],
      [],
    ),
  'getAllAPIKeys' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(APIKey)))],
      ['query'],
    ),
  'getAllCustomProviderMetadata' : IDL.Func(
      [],
      [IDL.Vec(CustomProviderMetadata)],
      ['query'],
    ),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderInfo)], ['query']),
  'getAllUsersCustomProviderMetadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CustomProviderMetadata)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Principal], ['query']),
  'getCustomProviderMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomProviderMetadata)],
      ['query'],
    ),
  'getProviderInfo' : IDL.Func([IDL.Text], [ProviderInfo], ['query']),
  'getProviderKey' : IDL.Func([IDL.Text], [IDL.Opt(APIKey)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkflowRuns' : IDL.Func([IDL.Text], [IDL.Vec(WorkflowRun)], ['query']),
  'initializeProviders' : IDL.Func([IDL.Vec(ProviderInfo)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'providerKeyExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomProviderMetadata' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'streamChatMessages' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'updateWorkflowRun' : IDL.Func(
      [IDL.Text, WorkflowRunStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [WorkflowRun],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkflowRunStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Text,
    'running' : IDL.Null,
  });
  const Time = IDL.Int;
  const WorkflowRun = IDL.Record({
    'id' : IDL.Text,
    'status' : WorkflowRunStatus,
    'provider' : IDL.Text,
    'inputs' : IDL.Text,
    'timestamp' : Time,
    'outputBlobId' : IDL.Opt(IDL.Text),
    'workflowType' : IDL.Text,
    'durationNanos' : IDL.Opt(IDL.Int),
  });
  const APIKey = IDL.Record({
    'key' : IDL.Text,
    'provider' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const CustomProviderMetadata = IDL.Record({ 'displayName' : IDL.Text });
  const ProviderInfo = IDL.Record({
    'documentationLink' : IDL.Text,
    'name' : IDL.Text,
    'author' : IDL.Text,
    'version' : IDL.Text,
    'apiEndpoint' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'provider' : IDL.Text,
    'fromSystem' : IDL.Bool,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateAPIKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelPendingWorkflowRunsForProvider' : IDL.Func([IDL.Text], [], []),
    'cancelWorkflowRun' : IDL.Func([IDL.Text], [], []),
    'customProviderMetadataExists' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'executeWorkflow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [WorkflowRun],
        [],
      ),
    'getAllAPIKeys' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(APIKey)))],
        ['query'],
      ),
    'getAllCustomProviderMetadata' : IDL.Func(
        [],
        [IDL.Vec(CustomProviderMetadata)],
        ['query'],
      ),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderInfo)], ['query']),
    'getAllUsersCustomProviderMetadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CustomProviderMetadata)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func([], [IDL.Principal], ['query']),
    'getCustomProviderMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomProviderMetadata)],
        ['query'],
      ),
    'getProviderInfo' : IDL.Func([IDL.Text], [ProviderInfo], ['query']),
    'getProviderKey' : IDL.Func([IDL.Text], [IDL.Opt(APIKey)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkflowRuns' : IDL.Func([IDL.Text], [IDL.Vec(WorkflowRun)], ['query']),
    'initializeProviders' : IDL.Func([IDL.Vec(ProviderInfo)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'providerKeyExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomProviderMetadata' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'streamChatMessages' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'updateWorkflowRun' : IDL.Func(
        [IDL.Text, WorkflowRunStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [WorkflowRun],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };