/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface APIKey {
  'key' : string,
  'provider' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export interface ChatMessage {
  'content' : string,
  'provider' : string,
  'fromSystem' : boolean,
  'timestamp' : Time,
}
export interface CustomProviderMetadata { 'displayName' : string }
export interface ProviderInfo {
  'documentationLink' : string,
  'name' : string,
  'author' : string,
  'version' : string,
  'apiEndpoint' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkflowRun {
  'id' : string,
  'status' : WorkflowRunStatus,
  'provider' : string,
  'inputs' : string,
  'timestamp' : Time,
  'outputBlobId' : [] | [string],
  'workflowType' : string,
  'durationNanos' : [] | [bigint],
}
export type WorkflowRunStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : string } |
  { 'running' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[string, string], undefined>,
  'addOrUpdateAPIKey' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelPendingWorkflowRunsForProvider' : ActorMethod<[string], undefined>,
  'cancelWorkflowRun' : ActorMethod<[string], undefined>,
  'customProviderMetadataExists' : ActorMethod<[string], boolean>,
  'executeWorkflow' : ActorMethod<[string, string, string], WorkflowRun>,
  'getAllAPIKeys' : ActorMethod<[], Array<[Principal, Array<APIKey>]>>,
  'getAllCustomProviderMetadata' : ActorMethod<
    [],
    Array<CustomProviderMetadata>
  >,
  'getAllProviders' : ActorMethod<[], Array<ProviderInfo>>,
  'getAllUsersCustomProviderMetadata' : ActorMethod<
    [],
    Array<[Principal, Array<CustomProviderMetadata>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUser' : ActorMethod<[], Principal>,
  'getCustomProviderMetadata' : ActorMethod<
    [string],
    [] | [CustomProviderMetadata]
  >,
  'getProviderInfo' : ActorMethod<[string], ProviderInfo>,
  'getProviderKey' : ActorMethod<[string], [] | [APIKey]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkflowRuns' : ActorMethod<[string], Array<WorkflowRun>>,
  'initializeProviders' : ActorMethod<[Array<ProviderInfo>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'providerKeyExists' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomProviderMetadata' : ActorMethod<[string, string], undefined>,
  'streamChatMessages' : ActorMethod<[string, bigint], Array<ChatMessage>>,
  'updateWorkflowRun' : ActorMethod<
    [string, WorkflowRunStatus, [] | [string], [] | [bigint]],
    WorkflowRun
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];